export { default as Navigation } from './Navigation';
export { default as Hero } from './Hero';
export { default as About } from './About';
export { default as Projects } from './Projects';
export { default as Experience } from './Experience';
export { default as Skills } from './Skills';
export { default as Awards } from './Awards';
export { default as Footer } from './Footer';
export { default as ScrollAnimation } from './ScrollAnimation';
